[tool.poetry]
name = "vcron"
version = "0.2.0"
description = ""
authors = ["laixintao <laixintaoo@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/laixintao/vcron"
license = "GPLv3"
keywords = ["python3"]
packages = [{include = "vcron"}]
include = [
    { path = "docs", format = "sdist" },
    { path = "tests", format = "sdist" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.8.1"
textual = "^0.45.0"
click = "^8.1.7"
cron-descriptor = "^1.4.0"
croniter = "^2.0.1"

[tool.poetry.scripts]
vcron = 'vcron.main:main'

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-asyncio = "^0.21.1"
ipdb = "^0.13.13"
flake8 = "^6.1.0"
pytest-cov = "^2.12.1"
bumpversion = "^0.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/laixintao/vcron/issues"


[tool.black]
line-length = 79
target-version = ['py37']
preview = true
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.coverage.run]
omit = [
]

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'if TYPE_CHECKING:',
    'if __name__ == "__main__":',
    '@overload',
    '__rich_repr__',
    '@abstractmethod',
    'NotImplementedError',
]

# ---
